#ifndef __DIFFTEST_DEF_H
#define __DIFFTEST_DEF_H


#if defined(CPU_NANHU)

#define CONFIG_NO_DIRTY_VS
#define CONFIG_DIFF_RVV
#define CONFIG_DIFF_FPU
#define CONFIG_DIFF_ZICOND
#define CONFIG_DIFF_ZICNTR
#define CONFIG_DIFF_ZIHPM
#define VARITH_AGNOSTIC_WRITE_ONE
#define CONFIG_DIFF_SDTRIG
#define CONFIG_DIFF_DEBUG_MODE


#define CONFIG_DIFF_ISA_STRING  "RV64IMAFDCV_zicond_zicntr_zihpm_sdtrig_zba_zbb_zbc_zbs_smrnmi"
#define CONFIG_MEMORY_SIZE     (16 * 1024 * 1024 * 1024UL)
#define CONFIG_FLASH_BASE      0x10000000UL
#define CONFIG_FLASH_SIZE      0x10000000UL
#define CONFIG_BLOCK_SIZE      128
#define CONFIG_PMP_NUM         16
#define CONFIG_PMP_MAX_NUM     16
#define CONFIG_PMP_GRAN        12
#define CONFIG_TRIGGER_NUM     4
#define CONFIG_MAX_PADDR_BITS  48
//#define CONFIG_MMU_CAPABILITY  IMPL_MMU_SV48
#define CONFIG_MISALIGNED      false 

#endif

#endif
